server:
  port: ${PORT:8086}

spring:
  application:
    name: payment-service
  
  # H2数据库配置
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2控制台
  h2:
    console:
      enabled: true
      path: /h2-console

# Eureka Client 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 更频繁地从注册中心获取服务列表
    registry-fetch-interval-seconds: 5
    # 初始实例信息复制延迟时间
    initial-instance-info-replication-interval-seconds: 5
    # 实例信息复制间隔时间
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    # 更频繁的心跳，更快检测到服务状态变化
    lease-renewal-interval-in-seconds: 5
    # 更短的过期时间，更快清理失效实例
    lease-expiration-duration-in-seconds: 15
    # 元数据，标识服务版本
    metadata-map:
      version: "1.0.0"
      startup: ${random.long}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      port: ${server.port}

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents,refresh
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true

# 应用信息
info:
  app:
    name: Payment Service
    description: Payment processing service with resilience patterns
    version: 1.0.0
    features:
      - Circuit Breaker (Resilience4j)
      - Retry Pattern
      - Timeout Control
      - Bulkhead Pattern
      - Multiple Payment Gateways
      - Fallback Mechanisms

# Resilience4j配置
resilience4j:
  # 熔断器配置
  circuitbreaker:
    instances:
      stripe-payment:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - com.shophub.payment.service.external.StripePaymentGateway$PaymentTimeoutException
          - com.shophub.payment.service.external.StripePaymentGateway$PaymentServiceUnavailableException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
      
      paypal-payment:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 60
        wait-duration-in-open-state: 15s
        automatic-transition-from-open-to-half-open-enabled: true
      
      payment-query:
        register-health-indicator: true
        sliding-window-type: time_based
        sliding-window-size: 60
        minimum-number-of-calls: 3
        failure-rate-threshold: 40
        wait-duration-in-open-state: 5s
  
  # 重试配置
  retry:
    instances:
      stripe-payment:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - com.shophub.payment.service.external.StripePaymentGateway$PaymentTimeoutException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
      
      paypal-payment:
        max-attempts: 2
        wait-duration: 2s
        exponential-backoff-multiplier: 1.5
      
      payment-query:
        max-attempts: 2
        wait-duration: 500ms
  
  # 超时控制配置
  timelimiter:
    instances:
      stripe-payment:
        timeout-duration: 3s
        cancel-running-future: true
      
      paypal-payment:
        timeout-duration: 5s
        cancel-running-future: true
  
  # 舱壁模式配置
  bulkhead:
    instances:
      stripe-payment:
        max-concurrent-calls: 5
        max-wait-duration: 1s
      
      paypal-payment:
        max-concurrent-calls: 3
        max-wait-duration: 2s
  
  # 线程池舱壁配置
  thread-pool-bulkhead:
    instances:
      stripe-payment:
        max-thread-pool-size: 4
        core-thread-pool-size: 2
        queue-capacity: 20
        keep-alive-duration: 20ms
      
      paypal-payment:
        max-thread-pool-size: 3
        core-thread-pool-size: 1
        queue-capacity: 10
        keep-alive-duration: 20ms

logging:
  level:
    com.shophub.payment: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"