server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: "configserver:"
  
  # 数据库配置 (H2内存数据库)
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2控制台配置 (开发环境)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Spring Cloud LoadBalancer 配置
  cloud:
    loadbalancer:
      retry:
        enabled: true
        # 重试次数
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: false
        retryable-status-codes: 500,502,503,504
      # 健康检查
      health-check:
        initial-delay: 1000ms
        interval: 10000ms

# Eureka Client 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  # Week 7: 分布式追踪配置
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

# Feign 客户端配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
      product-service:
        connect-timeout: 3000
        read-timeout: 8000
        logger-level: full
        # 重试配置
        retryer: 
          class: feign.Retryer.Default
          # 重试间隔：100ms, 最大间隔：1s, 最大重试次数：3
          period: 100
          max-period: 1000
          max-attempts: 3
      payment-service:
        connect-timeout: 5000
        read-timeout: 15000
        logger-level: full
        retryer:
          class: feign.Retryer.Default
          period: 200
          max-period: 2000
          max-attempts: 2
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true
  # 分布式追踪配置
  micrometer:
    enabled: true
        
# Resilience4j 配置 (熔断器和重试)
resilience4j:
  retry:
    instances:
      product-service:
        max-attempts: 3
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
      payment-service:
        max-attempts: 2
        wait-duration: 1s
        exponential-backoff-multiplier: 1.5
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      product-service:
        register-health-indicator: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
      payment-service:
        register-health-indicator: true
        failure-rate-threshold: 40
        wait-duration-in-open-state: 20s
        sliding-window-size: 8
        minimum-number-of-calls: 4
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - java.lang.RuntimeException
        ignore-exceptions:
          - java.lang.IllegalArgumentException

# 日志配置
logging:
  level:
    com.shophub.order: INFO
    org.springframework.cloud: DEBUG
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    io.github.resilience4j: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId:-}] %-5level [%logger{36}] - %msg%n"


---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: order-service

# Week 7: Docker 环境下的分布式追踪配置
management:
  tracing:
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans