# User Service 服务独有配置
# 只包含用户服务特定的业务配置

server:
  port: 8081

spring:
  application:
    name: user-service

# 用户服务特定配置
user:
  authentication:
    jwt-secret: ${JWT_SECRET:mySecretKey}
    token-expiration: 3600
    max-login-attempts: 5
    lockout-duration: 300
  registration:
    email-verification: true
    auto-activation: false
    password-policy:
      min-length: 8
      require-uppercase: true
      require-lowercase: true
      require-numbers: true
      require-special-chars: true
  profile:
    avatar-upload: true
    max-avatar-size: 2MB
    allowed-formats: ["jpg", "png", "gif"]

# 用户服务特性开关
feature:
  user:
    social-login: true
    two-factor-auth: false
    profile-verification: true
    activity-tracking: true

# 用户服务监控配置
management:
  metrics:
    tags:
      service: user-service

# 用户服务日志配置
logging:
  level:
    com.shophub.user: DEBUG
    org.springframework.security: INFO

---
# Docker profile - User Service 在 Docker 环境下的特定配置
spring:
  config:
    activate:
      on-profile: docker

# Docker 环境下的用户服务配置
user:
  docker:
    container-name: user-service
    health-check:
      interval: 30s
      timeout: 10s
      retries: 3
    resources:
      memory: 512m
      cpu: 0.5

# Docker 环境下的日志配置
logging:
  level:
    com.shophub.user: INFO
    org.springframework.security: WARN