server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
        git:
          uri: file://${user.home}/config-repo
          clone-on-start: true
          force-pull: true
  security:
    user:
      name: configuser
      password: configpass

# Eureka Client 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 更频繁地从注册中心获取服务列表
    registry-fetch-interval-seconds: 5
    # 初始实例信息复制延迟时间
    initial-instance-info-replication-interval-seconds: 5
    # 实例信息复制间隔时间
    instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    # 更频繁的心跳，更快检测到服务状态变化
    lease-renewal-interval-in-seconds: 5
    # 更短的过期时间，更快清理失效实例
    lease-expiration-duration-in-seconds: 15
    # 元数据，标识服务版本
    metadata-map:
      version: "1.0.0"
      startup: ${random.long}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.shophub.config: DEBUG
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"