# Development environment overrides
feature:
  recommendations:
    enabled: true
  realtime-inventory:
    enabled: false
  multi-currency:
    enabled: false

# dev环境下的Redis配置（用于限流）
spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0


payment:
  gateway:
    primary: stripe
    stripe:
      api-key: sk_test_dev_dummy
      webhook-secret: whsec_dev_dummy
    paypal:
      client-id: paypal_dev_dummy
      client-secret: paypal_dev_secret_dummy

logging:
  level:
    root: INFO
    com.shophub: DEBUG