# 通用配置文件 - 所有微服务共享的基础配置
# 包含Eureka、Management、Logging、Tracing等通用配置

# Eureka Client 通用配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 服务注册和发现的频率配置
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
  instance:
    prefer-ip-address: true
    # 心跳间隔
    lease-renewal-interval-in-seconds: 10
    # 更短的过期时间，更快清理失效实例
    lease-expiration-duration-in-seconds: 30
    # 元数据，标识服务版本
    metadata-map:
      version: "1.0.0"
      startup: ${random.long}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      port: ${server.port}

# 健康检查和监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,env,prometheus,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s
  # 分布式追踪配置
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

# 日志配置
logging:
  level:
    org.springframework.cloud: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    io.micrometer: INFO
    io.github.resilience4j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] [%X{traceId:-},%X{spanId:-}] - %msg%n"

# Spring Cloud LoadBalancer 通用配置
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: false
        retryable-status-codes: 500,502,503,504
      health-check:
        initial-delay: 1000ms
        interval: 10000ms

# Feign 通用配置
feign:
  retryer:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
        logger-level: BASIC

# 应用信息
info:
  app:
    name: ${spring.application.name}
    description: ShopHub microservice
    version: 1.0.0
    author: ShopHub Team
  build:
    version: ${project.version:1.0.0}
    timestamp: ${maven.build.timestamp:unknown}