# Order Service Docker环境配置
# 继承自 application-docker.yml 的通用Docker配置

spring:
  # Docker环境下的数据库配置
  datasource:
    url: jdbc:h2:mem:orderdb-docker
    driver-class-name: org.h2.Driver
    username: sa
    password: password

# Docker环境下的Eureka实例配置
eureka:
  instance:
    hostname: order-service
    prefer-ip-address: false