# Product Service Docker环境配置
# 继承自 application-docker.yml 的通用Docker配置

spring:
  # Docker环境下的数据库配置
  datasource:
    url: jdbc:h2:mem:productdb-docker
    driver-class-name: org.h2.Driver
    username: sa
    password: password

# Docker环境下的Eureka实例配置
eureka:
  instance:
    hostname: product-service
    prefer-ip-address: false

# Docker环境下的功能开关配置
feature:
  recommendations:
    enabled: true
    algorithm: collaborative-filtering
    max-results: 10
  realtime-inventory:
    enabled: true
    update-interval: 30s
  multi-currency:
    enabled: true
    default-currency: USD
    supported-currencies: USD,EUR,CNY,JPY