# User Service 特定配置
# 通用配置（Eureka、Management、Logging等）继承自 application.yml
# 环境特定配置继承自 application-{profile}.yml

server:
  port: 8081

spring:
  application:
    name: user-service
  # 数据库配置 (H2内存数据库)
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# Feature toggles
feature:
  recommendations:
    enabled: ${FEATURE_RECOMMENDATIONS_ENABLED:true}
    personalization: true
  realtime-inventory:
    enabled: ${FEATURE_REALTIME_INVENTORY_ENABLED:false}
  multi-currency:
    enabled: ${FEATURE_MULTI_CURRENCY_ENABLED:false}

# User service specific configuration
user:
  authentication:
    jwt-secret: ${JWT_SECRET:mySecretKey}
    token-expiration: 3600
  registration:
    email-verification: true
    auto-approve: false
  profile:
    max-upload-size: 5MB
    allowed-formats: jpg,png,gif

logging:
  level:
    com.shophub.user: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"